[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@forge-std/=node_modules/forge-std/src/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
]
optimizer = true
optimizer_runs = 1
solc = "0.8.10"

[profile.test]
via-ir = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
avax = "https://avax-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
avax_fuji = "https://avax-fuji.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

[etherscan]
avax = { key = "${API_KEY_SNOWSCAN}" }
avax_fuji = { key = "${API_KEY_SNOWSCAN}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
